// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/about.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/posts/index.tsx";
import * as $$0 from "./islands/Main.tsx";
import * as $$1 from "./islands/Navigator.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/about.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/posts/index.tsx": $3,
  },
  islands: {
    "./islands/Main.tsx": $$0,
    "./islands/Navigator.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
